name: admin_panel_candela
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.3
  firebase_database: ^10.4.8
  firebase_storage: ^11.6.4
  google_fonts: ^6.1.0
  flutter_tex: ^4.0.6
  file_picker: ^6.1.1
  cached_network_image: ^3.3.1
  firebase_auth: ^4.17.3
  firebase_ui_auth: ^1.12.1





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/



