// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcq4xzbxHrxSigNmLvbGKKapI1q2s-dE4',
    appId: '1:436107959923:web:214c5b0681375199335406',
    messagingSenderId: '436107959923',
    projectId: 'admin-panel-candela',
    authDomain: 'admin-panel-candela.firebaseapp.com',
    databaseURL: 'https://admin-panel-candela-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-panel-candela.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4VAHPIXbvkOwD8EHwE_I0g_5DCD5s4tg',
    appId: '1:436107959923:android:732ef414e8e0315d335406',
    messagingSenderId: '436107959923',
    projectId: 'admin-panel-candela',
    databaseURL: 'https://admin-panel-candela-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-panel-candela.appspot.com',
  );
}
